language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm start > /dev/null &
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal $BROWSERSTACK_KEY localhost,8001,0 > /dev/null &
- sleep 10
after_success:
- cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
addons:
  code_climate:
    repo_token: 4abde268e416aa3752bccf1311ecfe7cd3d6a445ff4849ee4632bc7f9bbde251
services:
- redis-server
sudo: false
env:
  global:
  - TRAVIS=true
  - PORT=3000
  - CHROME_EXTENSION_ID=none
  - OT_API_KEY=44935341
  - BROWSERSTACK_USERNAME=adamullman1
  - secure: MhMbegJo5b4kQIJkWwBwmdVMP9Vt16GP4FTz+gvVjsdoBIfR8g7tOLYtHh8pcw1Uy3noAZf54LKgcZ7ZI4G3xhfbw3r4TNN5+sCBDW+Lu3T5uvoxp0gr9E+Z2MVSr31KWapJVcFiTbQgPK6POQf84tIXprgPKTkfVQ+IpCz8pMXkqeyF9A4YUsP/pRE2ASJWoVa4AQYFykchRFWsXNABhQDXnst9137pnrQ91VFS+6pC0HEusxZWy3BowmLeWv2nIQPu8WHwADLdNKcNGnTEAqf5zFmtiUR02OaJSQKfWsfbeqEOy2+ZKzy+LHAOzOxvzktPnPH9eiXdpOkpsUv8QsvOF8Xntx4196ukmDaf73vV1d/sQZzhgIZkFp4fy3jRFrMagM94ctMOSzbz3/8FDBwvo72oCFsxOcS1h+jeMvU9tY23odsFpv9CQ0UowxlOD1N7bG2MSo2TxFSL+u/vzqwhDbWJUQFjMs+feLp+Zn/wDvKEG20lrLC9QY/3P8UhPBEifM9gt85imbNSeG1t8QaB6eMBRIg/SEHZTzaYsZxhx1m4BIXiWKIzCxdanM9wUwUP9KS0mAhgsvY8Y/6ZyIr655KoZrR/Pj99UlidxOacId4j47zaHK5VnbXb9E/MVVPr0s/XDT/3rkObRsMrS+Ye8vF4LJTHm/yphbOqa38=
  - secure: P8S9S456B2NjkLcqgTsmnXqXYv1TuW6APRRSyArUlKrrSA7V5RLaZQWI8Bot96nEjmUqKOGZ+hzxqminaSmasYkJEGAIXZleCHXi7lSxU6ObzRNhjMdFqTT9q+I4xRZHjOHJnKmH+gf2+sXXI2620omjHMZt+0bzy8mPayEZHALxMHYTHdqIOr2u6EsdvS30bqbQMdRiYe4FcjFk9JIf2bg9oo+m9+boBqLyr5oGG8GAPYqnKjJbjIM6hJYuomO5kWNPCHEYjtfFS2eHKwvVUoO6ncgAecVPs1n6ZS1jqTV7i42Ig8cuLq8JubemYnFdeUpv+8lt1ds6/1xQO1wnmJWjQ0m0p5dlbxu2GkW4jmG9fMudC7+pWxOegmzx7TyGjK20IvqmBMST2Jl9TVpav9tOvyex5sttGzN0rT/vGWuc3xUOfD3dXBVDm7wJFf1DHD5SaKjGQZCKHXCn6D1p21a7j9R5jIKFCzt+cp7W9EJNe9rUSmr20iqaKAg/MavW4a93UsWMctxhW6+GR4XCJDM+a0enPWVZEWKwgyPn6DxSUeIloG0tkL7Ag61nh39d43dHuWqzztxX97Qa9Hwk9VZa7OQEyRo6jGlqjTxNjtbnQ8ZYlpUOT84+Ujn/x2VrpCIy9pKPvxnBqQO3G7St2Ipg4eV04Yyhzz+JmcuLlxU=
